# Generated by Django 3.1.3 on 2020-12-10 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='large_stock',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='medium_stock',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='small_stock',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
