# Generated by Django 3.1.2 on 2020-10-21 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messageboard', '0002_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='messageboard.topic'),
            preserve_default=False,
        ),
    ]
