# Generated by Django 3.1.2 on 2020-10-26 20:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('messageboard', '0002_auto_20201026_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discussion',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='messageboard.topic'),
        ),
    ]
