# Generated by Django 3.1.2 on 2020-10-27 23:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageboard', '0004_remove_discussion_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
