# Generated by Django 3.1.2 on 2020-10-27 23:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageboard', '0005_topic_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
