# Generated by Django 3.1.2 on 2020-10-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageboard', '0006_discussion_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='image',
            field=models.ImageField(blank=True, upload_to='imageuploads/'),
        ),
    ]
