# Generated by Django 3.1.2 on 2020-10-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageboard', '0007_discussion_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, upload_to='imageuploads/'),
        ),
    ]
