# Generated by Django 3.1.4 on 2020-12-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageboard', '0009_auto_20201105_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
