# Generated by Django 3.1.4 on 2020-12-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20201213_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('Delayed', 'Delayed'), ('Shipped', 'Shipped'), ('In Progress', 'In Progress')], default='Received', max_length=100),
        ),
    ]
